spring:
  mongodb:
    uri: mongodb://root:example@mongo/assignment_user?authSource=admin&readPreference=primary&appname=MongoDB%20Compass&ssl=false&maxPoolSize=50&connectTimeoutMS=2000
    database: userAssignment
  cloud:
    gateway:
      routes:
        - id: training-service
          uri: lb://training-service
          predicates:
            - Path=/api/training/**
          filters:
            - name: CircuitBreaker
              args:
                name: training-service
                fallbackuri: forward:/trainingServiceFallback
        - id: finance-service
          uri: lb://finance-service
          predicates:
            - Path=/api/finance/**
          filters:
            - name: CircuitBreaker
              args:
                name: finance-service
                fallbackuri: forward:/financeServiceFallback
        - id: resource-service
          uri: lb://resource-service
          predicates:
            - Path=/api/resource/**
          filters:
            - name: CircuitBreaker
              args:
                name: resource-service
                fallbackuri: forward:/resourceServiceFallback
        - id: user-service
          uri: lb://resource-service
          predicates:
            - Path=/api/user/**
          filters:
            - name: CircuitBreaker
              args:
                name: resource-service
                fallbackuri: forward:/resourceServiceFallback
        - id: zipkin-service
          uri: http://zipkin-server:9411
          predicates:
            - Path=/api/v2/**
hystrix:
  command:
    fallback:
      isolation:
        thread:
          timeoutInMilliseconds: 5000 
eureka:
  instance:
    preferIpAddress: true
  client:
    register-with-eureka: true
    fetchRegistry: true
    service-url:
      defaultZone: ${EUREKA_SERVER:http://localhost:9004/eureka/}
    enabled: true  
